version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-twitter-ads
            source /usr/local/share/virtualenvs/tap-twitter-ads/bin/activate
            pip install -U 'pip<19.2' 'setuptools<51.0.0'
            pip install .[dev]
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-twitter-ads/bin/activate
            pip install coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_twitter_ads --cover-html-dir=htmlcov tests/unittests
            coverage html
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-twitter-ads/bin/activate
            pylint tap_twitter_ads -d C,R,W
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_twitter_ads/schemas/*.json
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          no_output_timeout: 60m
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-twitter-ads tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
